Simple space view
dengaku-club/animium.js pull request #6
Opened 2017-08-13 12:01 UTC by dadaa

2017-08-13 12:35 UTC, shundroid requested changes

2017-08-13 12:35 UTC, shundroid commented on src/manage/index.html
> +      for (let record of records) {
そいえばここって const でもいいらしいですね

2017-08-13 12:38 UTC, dadaa commented on src/manage/index.html
> +      for (let record of records) {
あ。そうでしたねー

2017-08-14 01:16 UTC, shundroid approved these changes

2017-08-14 01:17 UTC, merged